[workspace]
members = [".", "crates/sl-mpc-derive", "crates/sl-mpc-vrf"]
resolver = "2"

[package]
name = "multi-party-schnorr"
version = "1.3.0-pre.9"
edition = "2021"
license-file = "LICENSE"
description = "Multi party Schnorr protocol"
repository = "https://github.com/silence-laboratories/multi-party-schnorr"
keywords = ["mpc", "threshold_signatures", "schnorr"]
readme = "README.md"
rust-version = "1.88"

[[example]]
name = "sign"
required-features = [ "eddsa", "test-support" ]

[[example]]
name = "keygen"
required-features = [ "eddsa", "test-support" ]

[[example]]
name = "refresh"
required-features = [ "eddsa", "test-support" ]

[features]
default = ["eddsa", "session"]
eddsa = ["curve25519-dalek", "ed25519-dalek", "dep:sl-mpc-derive", "sl-mpc-derive/eddsa"]
vrf = ["eddsa", "serde", "sl-mpc-derive/vrf", "dep:sl-mpc-vrf", "sl-mpc-vrf/serde"]
taproot = ["k256/schnorr"]
redpallas = ["dep:pasta_curves", "dep:group", "dep:rand_core", "dep:blake2b_simd", "dep:reddsa"]
keyshare-session-id = []
serde = [
  "dep:serde",
  "dep:serde_bytes",
  "serde/alloc",
  "serde_bytes/alloc",
  "curve25519-dalek/serde",
  "ed25519-dalek/serde",
  "k256/serde",
  "k256/pkcs8",
  "sl-mpc-mate/serde",
  "crypto_box/serde",
  "pasta_curves?/serde",
]
session = ["serde", "dep:ciborium"]
test-support = ["rand/std", "rand/std_rng"]

[dependencies]
sl-mpc-derive = { version = "0.1.0", optional = true, default-features = false }
sl-mpc-vrf = { version = "0.1.0-pre.4", optional = true, default-features = false }
zeroize = { version = "1.6.1", default-features = false, features = ["zeroize_derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
serde_bytes = { version = "0.11.15", default-features = false, optional = true }
signature = { version = "2.2.0", default-features = false }
bytemuck = { version = "1.22", default-features = false, features = [
  "derive",
  "min_const_generics",
  "extern_crate_alloc",
] }
elliptic-curve = { version = "0.13", default-features = false, features = ["arithmetic"] }
ed25519-dalek = { version = "2.1.0", default-features = false, features = [
  "alloc",
  "zeroize",
  "rand_core",
  "digest",
], optional = true }
curve25519-dalek = { version = "~4.1.3", default-features = false, features = [
  "alloc",
  "digest",
  "group",
], optional = true }
k256 = { version = "0.13.2", default-features = false, optional = true }
crypto-bigint = { version = "0.5", default-features = false, features = ["rand_core"] }
rand = { version = "0.8", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10.7", default-features = false }
crypto_box = { version = "0.9.1", default-features = false, features = ["alloc", "rand_core", "salsa20"] }
ff = { version = "0.13.0", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
sl-mpc-mate = { version = "1.1.1", default-features = false }
thiserror = { version = "2", default-features = false }
derivation-path = { version = "0.2.0", default-features = false }
hmac = { version = "0.12.1", default-features = false }
ciborium = { version = "0.2", default-features = false, optional = true }
group = { version = "0.13.0", optional = true }
pasta_curves = { version = "0.5", default-features = false, optional = true }
rand_core = { version = "0.6.4", optional = true }
reddsa = { version = "0.5", default-features = false, optional = true, features = ["alloc"] }
blake2b_simd = { version = "1", default-features = false, optional = true }

[dev-dependencies]
rand = { version = "0.8", features = ["std", "std_rng"] }
k256 = { version = "0.13.2" }
bs58 = "0.5.0"
ciborium = "0.2"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread"] }
