// Copyright (c) Silence Laboratories Pte. Ltd. All Rights Reserved.
// This software is licensed under the Silence Laboratories License Agreement.

use rand::RngCore;
use sha2::{Digest, Sha256};

use crate::common::utils::SessionId;

/// Client-side helper for DKG protocol
pub struct DkgClient;

impl DkgClient {
    /// Generate a unique session ID for a DKG session
    /// In production, this should be generated by the client and be unique
    pub fn generate_session_id() -> SessionId {
        let mut rng = rand::thread_rng();
        let mut session_id = [0u8; 32];
        rng.fill_bytes(&mut session_id);
        session_id
    }

}
