name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@1.78
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "build"

    - name: Run cargo clippy
      run: cargo clippy --all --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features --release
