name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@1.88
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "build"

    - name: Run cargo clippy (EdDSA + Taproot + RedPallas + session)
      run: cargo clippy --all --no-default-features --features "eddsa taproot redpallas session keyshare-session-id test-support" --locked -- -D warnings

    - name: Run cargo clippy (EdDSA + associated-data)
      run: cargo clippy --all --no-default-features --features "eddsa ad session keyshare-session-id test-support" --locked -- -D warnings

    - name: Run tests (EdDSA + Taproot + RedPallas + session)
      run: cargo test --release --no-default-features --features "eddsa taproot redpallas session keyshare-session-id test-support" --locked

    - name: Run tests (EdDSA + associated-data)
      run: cargo test --release --no-default-features --features "eddsa ad session keyshare-session-id test-support" --locked
